services:
  # 1. Service ของ Next.js (Portfolio)
  web:
    container_name: portfolio_web
    build: .
    restart: always
    ports:
      - "8100:3000"
    environment:
      NODE_ENV: production

  # 2. Service ของ Nginx Proxy
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    network_mode: "host" # เชื่อมต่อกับ localhost:8100 ของเครื่องได้ทันที
    volumes:
      # เชื่อมโยง Config และ SSL จากเครื่องจริงเข้า Container
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # หากไฟล์เว็บโปรเจกต์อื่น (เช่น elitefund) อยู่ใน /var/www ให้เชื่อมไปด้วย
      - /var/www:/var/www:ro
