import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Providers from "./(main)/providers";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Navbar from "@/components/Navbar/Navbar";
import { Anuphan } from "next/font/google";

const anuphan = Anuphan({
  subsets: ["thai"],
  weight: ["400"],
});
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyWeb App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="th" suppressHydrationWarning>
      <body className={anuphan.className}>
        <Providers session={session}>
          {/* <Navbar /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
