import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wave Nanthawat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-aurora">
      <body className={`${inter.className} antialiased`}>
        <div className="relative min-h-full overflow-hidden">
          <div className="pointer-events-none absolute inset-0 bg-noise" />
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
