import type { Metadata } from "next";
import "./globals.css";
import { getServerSession } from "next-auth";
import Providers from "./(main)/providers";
import { authOptions } from "@/src/app/api/auth/[...nextauth]/route";
import { Anuphan } from "next/font/google";

const anuphan = Anuphan({
  subsets: ["thai"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Elite Fund",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    icon: [
      {
        url: "/logoEF-v2.png",
        sizes: "500x500",
        type: "image/png",
      },
      {
        url: "/logoEF-v2.png",
        sizes: "500x500",
        type: "image/png",
      },
    ],
    apple: {
      url: "/logoEF-v2.png",
      sizes: "180x180",
      type: "image/png",
    },
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="th" suppressHydrationWarning>
      <body className={anuphan.className}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
