name: Auto Deploy

on:
  push:
    branches:
      - Elite-Fund-web

jobs:
  merge-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Elite-Fund-web into build
        run: |
          git checkout build || git checkout -b build
          git merge Elite-Fund-web
          git push origin build

      - name: Deploy with Docker
        run: |
          cd ~/EliteFoundWeb
          git reset --hard
          git pull origin build
          docker compose down
          docker compose up -d --build
